import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import NavigationMenu from "./components/NavigationMenu";
import Footer from "./components/Footer";
import WhatsappContact from "./components/Whatsapp";


const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
        lang="en"
        suppressHydrationWarning
      >
        {/* Flex container to enable sticky footer */}
        <div className="flex flex-col min-h-screen">
          {/* Navigation Menu */}
          <NavigationMenu />

          {/* Main content area */}
          <main className="flex-grow">{children}</main>


          <WhatsappContact />
          {/* Sticky Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
